### ISSUE TITLE
checkboxes without value are not properly deserialized

### ISSUE THREAD

**Issue by rillig** [kflorence/jquery-deserialize#19]
In my current project I used a checkbox like this:

    <input type="checkbox" name="setting1" checked="checked">

The deserialize code doesn't handle this checkbox as I intended it because of the `if ( current.value == value ) ` line in the code. My checkbox doesn't have a `value`, so the current code just skips it.

According to http://stackoverflow.com/q/11424037, the HTML above seems standard-conformant to me, so it would be nice if your deserializer could handle it, or document it explicitly that only checkboxes with value are supported.

By the way, current Chrome and Firefox handle it well (reporting `element.value === "on"` if it is missing), but my old Safari has the above problem.

**Comment by blopker** [comment]
I'd just like to point out that according to spec, all `type="checkbox"` inputs are required to have a `value` attribute. So, this is invalid HTML.

See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

```
value:
The initial value of the control. This attribute is optional except when the value of the type attribute is checkbox.
```

**Comment by rillig** [comment]
Oops. Sorry for the “bug” report. I’ll go now and fix my broken HTML.
