### ISSUE TITLE
Does not work with nested field names

### ISSUE THREAD

**Issue by danyj** [kflorence/jquery-deserialize#28]
Nice script but only seems to work with simple names , something like this does not work

```
<form>
  <input type="text" name="foo[bar]" value="a value">
  <input type="text" name="foo[baz][quux]" value="another value">
</form>
```

**Comment by kflorence** [comment]
@danyj can you be more specific? That should work fine.

**Comment by danyj** [comment]
@kflorence  I tested bit more and it looks like it does change data but is not triggering any change events 

http://screencast.com/t/CPcR69pGwst

and I also have these kind of checkboxes http://prntscr.com/8nl8fk that work ok on normal change event , for example I get to switch them via this 


				if($type == 'switch' || $type == 'checkbox'){
					
					if($value == 1){
						$($selector).prop('checked', true).trigger('change');
					}else{
						$($selector).prop('checked', false).trigger('change');
						
					}
				}

**Comment by danyj** [comment]
This is the switch  http://sourcebox.io/446bc93a03f368d2f019df2b479154e9/html

**Comment by kflorence** [comment]
@danyj this plugin isn't doing anything special with values, it is just assigning them directly to the DOM element via the value property. You can pass in an `options` object as the second argument to `.deserialize()` which will allow you to react to each changed input via the `change` option, perhaps that will help?

**Comment by kflorence** [comment]
@danyj I haven't had much free time lately to look into this, if it's still a problem can you make a test case for it in the `tests` folder? The test should fail as described above.

**Comment by kflorence** [comment]
Please re-open with a test case if this is still an issue.
