### ISSUE TITLE
Minified version does not properly deserialize some selects

### ISSUE THREAD

**Issue by rodrigodiez** [kflorence/jquery-deserialize#29]
Sorry that I can not provide a full example right now. My select has URLs as its options values and a name. Tried with serialize() and serializeArray() serialization methods but no luck deserializing.

As soon as I included the non-minified version of the plugin it started working

**Comment by kflorence** [comment]
@rodrigodiez apologies, looks like the dist file hasn't been updated for awhile. Getting that fixed.

**Comment by kflorence** [comment]
Fix available as 1.3.3 https://github.com/kflorence/jquery-deserialize/releases/tag/1.3.3
