### ISSUE TITLE
with disabled  the deserialize not working

### ISSUE THREAD

**Issue by al-ani** [kflorence/jquery-deserialize#34]
Hi
I try you use the deserialize function it is working fine, but when I added disabled, the deserialize is not working anymore.

**Comment by kflorence** [comment]
The plugin filters out disabled inputs by design, see: https://github.com/kflorence/jquery-deserialize/blob/master/src/jquery.deserialize.js#L19

**Comment by kflorence** [comment]
@al-ani add4506c08257bb89816dad6e203562b72fde0da will allow you to provide a custom input filter when calling `deserialize`. Note, however, that while this will allow you to deserialize data to disabled inputs, disabled inputs will still _not_ be serialized. See: https://www.w3.org/TR/html401/interact/forms.html#h-17.13.2
