### ISSUE TITLE
npm install: missing files

### ISSUE THREAD

**Issue by danikane** [kflorence/jquery-deserialize#35]
Hi, npm install outputs only /src dir, package.json and readme.md.
No /dist so no minified file.

```
$ npm -v
3.10.3
```

```
$ npm install jquery-deserialize --save
******************
`-- jquery-deserialize@1.3.3
```

Thanks!

**Comment by kflorence** [comment]
@danikane Thanks for reporting. Resolved as 8770e9c6a9a75484acb5cfe591883d6206ff560e.
