### ISSUE TITLE
Force adding options to multi select

### ISSUE THREAD

**Issue by datatrippers** [kflorence/jquery-deserialize#38]
Hi!
I am using the select2 box in combination with jquery Deserialize, which works perfectly when not using ajax.
When using the ajax plugin, the options arent in the < select>< /select>, because they are not loaded yet (you have to search first).

Is it possible to make an 'force option', where the option is added to the <select> like:
< option value="{ID}"></option>

The name would be empty, since its not safed with serializing. 
When its in the < select>, i can use select2 to load the name again.

Thnx!

**Comment by kflorence** [comment]
@datatrippers  Sorry, I don't quite follow. Can you post an example somewhere?
