### ISSUE TITLE
Error when loading the plugin

### ISSUE THREAD

**Issue by jnegron357** [kflorence/jquery-deserialize#45]
I'm getting the following error when loading:

jquery.deserialize.js:241 Uncaught TypeError: Cannot read property 'noop' of undefined
    at jquery.deserialize.js:241
    at jquery.deserialize.js:30
    at jquery.deserialize.js:32
(anonymous) @ jquery.deserialize.js:241
(anonymous) @ jquery.deserialize.js:30
(anonymous) @ jquery.deserialize.js:32

**Comment by kflorence** [comment]
@jnegron357 make sure you have jQuery included on the page
