### ISSUE TITLE
Dual licence

### ISSUE THREAD

**Issue by Herz3h** [kflorence/jquery-deserialize#47]
I see that project has GPLv2 and MIT dual license.I  would like to use this in a commercial project ? Does this mean I can choose MIT licence and ignore GPLv2 ?

Thank you

**Comment by kflorence** [comment]
Hello @Herz3h -- yes the intent was to allow the user to choose one of those two licenses. Whichever you don't choose you can ignore.

**Comment by Herz3h** [comment]
amazing, thank you for clarification and the library
