### ISSUE TITLE
Will there be a new release?

### ISSUE THREAD

**Issue by turbolego** [kflorence/jquery-deserialize#48]
Latest release is 1.3.7 and the "release candidate" (2.0.0-rc1) made in 2017 has still not been released.

In the [notes of 2.0.0-rc1](https://github.com/kflorence/jquery-deserialize/releases) it says:

>Note that this is a release candidate, it will be marked stable once users have confirmed that there are no regressions.

Is there any news about this?

Thanks! 😄

**Comment by kflorence** [comment]
I suppose it is stable since I haven't heard anything since then :) Probably can officially release `2.0.0`.

**Comment by kflorence** [comment]
https://github.com/kflorence/jquery-deserialize/releases/tag/2.0.0
